version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo Installing dependencies...
        - npm ci
    build:
      commands:
        - echo Building the project...
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
